### ISSUE TITLE
[BUG] 保存配置失败

### ISSUE THREAD

**Issue by Moyf** [xhuajin/obsidian-settings-management#1]
![image](https://github.com/xhuajin/obsidian-settings-management/assets/4013062/bb8da363-543b-41db-8b7b-ec6466881488)

断点了一下，看到：
![image](https://github.com/xhuajin/obsidian-settings-management/assets/4013062/600efdf2-cf13-4ce5-af42-5ce4e874d7e8)

**Comment by xhuajin** [comment]
修好了，昨天优化的时候改漏了，感谢告知

**Comment by Moyf** [comment]
（好像还没有进 Release， BRAT 拉不到

**Comment by xhuajin** [comment]
可能是因为我没有换版本号，还是1.0.2。
