### ISSUE TITLE
[FR] 希望能给保存的插件预设设置图标

### ISSUE THREAD

**Issue by Moyf** [xhuajin/obsidian-settings-management#3]
![image](https://github.com/xhuajin/obsidian-settings-management/assets/4013062/02e6e3e8-c1f6-48de-b557-4206ffca0b85)

目前都是统一的拼图icon，希望可以给它们设置不同的图标以便区分

**Comment by xhuajin** [comment]
1.0.5 加上了插件预设图标的功能，暂时只能加 lucide 图标。

**Comment by Moyf** [comment]
嗯嗯，没问题！很有帮助了！

**Comment by Moyf** [comment]
（顺便，发现更新之后——虽然现在老版本用户应该还不多哈哈——老的没有设置图标的配置就没法正常显示了：
![image](https://github.com/xhuajin/obsidian-settings-management/assets/4013062/be37d7b5-b0ca-4988-b632-65b1ac1c399e)

我自己进 data.json 改掉啦~ 就顺便提一嘴 √
